# Generated by Django 6.1 on 2026-08-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_host', models.CharField(default='localhost', max_length=255)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer')], max_length=20)),
                ('field_key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('email', 'Email'), ('text', 'Text')], default='string', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Choices, for enum fields', null=True)),
                ('is_required_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('entity', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='Superadmin username who performed the action', max_length=150)),
                ('action', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.fieldcatalog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'field')},
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.SlugField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'module_key')},
            },
        ),
    ]
