# Generated by Django 6.1 on 2026-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='db_port',
            field=models.CharField(default='3306', max_length=10),
        ),
    ]
