# Generated by Codex on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_FEATURES = [
    {
        'key': 'employees',
        'label': 'Employees',
        'description': 'Employee records and employee-specific fields.',
        'entity': 'employee',
        'sort_order': 10,
    },
    {
        'key': 'customers',
        'label': 'Customers',
        'description': 'Customer records and customer-specific fields.',
        'entity': 'customer',
        'sort_order': 20,
    },
    {
        'key': 'inventory',
        'label': 'Inventory',
        'description': 'Inventory subscription option.',
        'entity': None,
        'sort_order': 30,
    },
    {
        'key': 'billing',
        'label': 'Billing',
        'description': 'Billing subscription option.',
        'entity': None,
        'sort_order': 40,
    },
]

DEFAULT_PLANS = [
    {
        'key': 'basic',
        'name': 'Basic',
        'description': 'Core employee and customer record management.',
        'feature_keys': ['employees', 'customers'],
        'sort_order': 10,
    },
    {
        'key': 'operations',
        'name': 'Operations',
        'description': 'Operational record management with inventory.',
        'feature_keys': ['employees', 'customers', 'inventory'],
        'sort_order': 20,
    },
    {
        'key': 'enterprise',
        'name': 'Enterprise',
        'description': 'All available platform features.',
        'feature_keys': ['employees', 'customers', 'inventory', 'billing'],
        'sort_order': 30,
    },
]


def seed_features_and_plans(apps, schema_editor):
    Feature = apps.get_model('tenants', 'Feature')
    Plan = apps.get_model('tenants', 'Plan')
    PlanFeature = apps.get_model('tenants', 'PlanFeature')
    TenantModule = apps.get_model('tenants', 'TenantModule')
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantSubscription = apps.get_model('tenants', 'TenantSubscription')

    feature_by_key = {}
    for row in DEFAULT_FEATURES:
        feature, _ = Feature.objects.update_or_create(
            key=row['key'],
            defaults={
                'label': row['label'],
                'description': row['description'],
                'entity': row['entity'],
                'sort_order': row['sort_order'],
                'is_active': True,
            },
        )
        feature_by_key[row['key']] = feature

    for row in DEFAULT_PLANS:
        plan, _ = Plan.objects.update_or_create(
            key=row['key'],
            defaults={
                'name': row['name'],
                'description': row['description'],
                'sort_order': row['sort_order'],
                'is_active': True,
            },
        )
        for feature_key in row['feature_keys']:
            PlanFeature.objects.get_or_create(plan=plan, feature=feature_by_key[feature_key])

    for entitlement in TenantModule.objects.all():
        feature = feature_by_key.get(entitlement.module_key)
        if feature and entitlement.feature_id != feature.id:
            entitlement.feature_id = feature.id
            entitlement.save(update_fields=['feature'])

    for tenant in Tenant.objects.all():
        TenantSubscription.objects.get_or_create(tenant=tenant, defaults={'plan': None, 'status': 'active'})


def unseed_features_and_plans(apps, schema_editor):
    Plan = apps.get_model('tenants', 'Plan')
    Feature = apps.get_model('tenants', 'Feature')

    Plan.objects.filter(key__in=[row['key'] for row in DEFAULT_PLANS]).delete()
    Feature.objects.filter(key__in=[row['key'] for row in DEFAULT_FEATURES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_db_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entity', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='tenants.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='tenants.plan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', through='tenants.PlanFeature', to='tenants.feature'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_entitlements', to='tenants.feature'),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='tenants.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
        migrations.RunPython(seed_features_and_plans, unseed_features_and_plans),
    ]
